# 单例模式
spring:
  application:
    name: ad-eureka

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    # eureka.client.fetch-registry: 表示是否从 Eureka Server 获取注册信息，默认为true。如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，设为false
    fetch-registry: false
    # eureka.client.register-with-eureka: 表示是否将自己注册到 Eureka Server, 默认为true。由于当前应用就是 Eureka Server, 因此设为 false
    register-with-eureka: false
    # 设置 Eureka Server 所在的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


# 配置不同的 Profile, 需要注意, 如果要执行下面的 Profile, 需要将上面的配置注释掉

# 多实例模式
---
#------------server1
#spring:
#  application:
#    name: ad-eureka
#  profiles: server1
#server:
#  port: 8501
#eureka:
#  instance:
#    hostname: server1
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server2:8502/eureka,http://server3:8503/eureka
#---
##------------server2
#spring:
#  application:
#    name: ad-eureka
#  profiles: server2
#server:
#  port: 8502
#eureka:
#  instance:
#    hostname: server2
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8501/eureka,http://server3:8503/eureka
##---------------------
#---
##------------server3
#spring:
#  application:
#    name: ad-eureka
#  profiles: server3
#server:
#  port: 8503
#eureka:
#  instance:
#    hostname: server3
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8501/eureka,http://server2:8502/eureka #切记逗号之间不能有空格
