server:
  port: 9001
spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:9000/eureka/

zuul:  #127.0.0.1:9001/hx/ad-sponsor/create/adPlan
  prefix: /hx
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false
